version: '3.8' 
services:
  notebooks:
    build: 
      context: data-science/.
      dockerfile: Dockerfile
    container_name: search-data-science
    ports:
      - 7077:7077 # Spark Master
      - 8082:8080 # Spark Master UI - 8082 less likely to conflict
      - 8081:8081 # Spark Worker UI
      - 4040:4040 # Spark UI
      - 4041:4041 # Spark UI
      - 8888:8888 # Jupyter Notebook UI 
      - 2345:2345 # Search Webserver 
    depends_on:
      - solr
    networks:
      - solr-data-science
    restart: unless-stopped
    environment:
      #PYSPARK_SUBMIT_ARGS: '--jars /usr/local/spark/lib/spark-solr-4.0.0-shaded.jar pyspark-shell'
      #NB_USER: 'search'
      #NB_UID: 1010
      #NB_GID: 1020
      #CHOWN_HOME: 'yes'
      #CHOWN_HOME_OPTS: -R    
      SOLR_HOST: 'search-solr'
    volumes:
      - type: bind
        source: "./data-science/notebooks/"
        target: "/tmp/notebooks/"
  solr:
    build:
      context: solr/.
      dockerfile: Dockerfile
    container_name: search-solr
    hostname: search-solr
    ports:
      - 8983:8983 
    environment:
      - ZK_HOST=search-zk:2181
      - SOLR_HOST=search-solr
    networks:
      - zk-solr
      - solr-data-science
    restart: unless-stopped
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:3.5.8
    container_name: search-zk
    hostname: search-zk
    ports: 
      - 2181:2128
    networks:
      - zk-solr
      - solr-data-science
    restart: unless-stopped

networks:
  zk-solr:  
  solr-data-science:
