version: '3'
services:
  solr:
    image: search-solr
    expose:
      - "8983"
    ports:
      - "8983:8983"
    environment:
      SERVER_HOST: "0.0.0.0"
    volumes:
      - search-solr-data:/usr/share/solr/data
    deploy:
      resources:
        limits:
          memory: "1g"
volumes:
  search-solr-data:
    driver: local
